# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- release-browser

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'
  displayName: 'Execute npm install'

- task: IonicCommand@1
  inputs:
    ionicCommand: 'cordova build'
    ionicArgs: 'browser'
    ionicVersion: '3.20.1'
    cordovaVersion: '8.1.2'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'www'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/public'
  displayName: 'Copy files to deploy'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/firebase.json'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy firebase.json for deployment setup'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'package'
    publishLocation: 'Container'